---
name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  integrity_checks:
    name: Integrity Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: scripts/setup
      - run: pipenv run tests
      - run: scripts/lint
