---
name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  server_integrity_checks:
    name: Server integrity checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: scripts/setup
      - run: pipenv run test
      - run: pipenv run lint
      - run: scripts/lint
